parameters: {}
packages:
  - name: bryce-bot
    functions:
      - name: reply
        binary: false
        main: main
        runtime: "nodejs:18"
        web: true
        parameters: {}
        environment:
          ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
        limits:
          timeout: 25000
          memory: 512
